### PR TITLE
typo in admin API spec

### PR DESCRIPTION
**Pull request by kartsims**
# Overview

There is a small typo in the API specs

# Changes

- Updated the label in the YML file, as well as the JSON file

# Implementation Details

Changed both files, but if one is generated by the other, please let me know in case I find others

### CODE REVIEW

**Comment by unnawut** [comment]
@mederic-p Would this conflict with #542 you're working on? Otherwise I'll merge it.

**Comment by T-Dnzt** [comment]
Hey @kartsims, thanks for your PR! We're currently refactoring and splitting the whole Swagger spec files and we'll make sure your changes are included as part of the update. Leaving this open until the PR for it is out with the correct changes.

**Comment by mederic-p** [comment]
Yep, it'll indeed conflict with the spec refactoring in progress. I've fixed this typo in the refactor, thanks!

**Comment by unnawut** [comment]
Closing as this is now reflected in #542:
- https://github.com/omisego/ewallet/pull/561/files#diff-d90769dc2c22ab274b5a717aebd70deeR5
- https://github.com/omisego/ewallet/pull/561/files#diff-3da6b7965078f7624f66d41f261b97ccR466

Thanks @kartsims!

**Pull request closed without merging**
