### PR TITLE
Update README with build requirements & Gitter

### PR DESCRIPTION
**Pull request by unnawut**
Issue/Task Number: T396 & T400

# Overview

Adds a list of commands that are required to be run successfully for a build to pass. Also replaces Rocket Chat with Gitter.

# Changes

- Added required build commands:
  - `mix format`
  - `mix credo`
  - `mix dialyzer`
  - `mix test`
- Replaces all occurrences of Rocket Chat with Gitter

# Implementation Details

Now that we have more contributors to the project and more checks during the build, it's good to have a list of required commands in the readme.

We discussed in Gitter that an example hook would be nice. However I realized that we have multiple ways to setup the development environment for eWallet so I'm simply listing the required commands here.

### CODE REVIEW

**Comment by unnawut** [comment]
I don't think "Contributing" section is the best place but I'm not sure where else it could be. So I'm putting it there first and asking for your opinions :p

**Comment by unnawut** [comment]
Don't we want the build to fail even with linting issues though? It's enforcing some good habits I think.

**Comment by unnawut** [comment]
But yes, reporting issues back as GitHub comments would be reallyyy useful!

**Comment by sirn** [comment]
Better to just block PR merge with comment/review block because it's annoying when build fails due to styling issue rather than regression (because actual test failures are not shown until styling issues are fixed).

**Comment by unnawut** [comment]
> because actual test failures are not shown until styling issues are fixed

Very good point. +1.

**Comment by MIKEISCHRIS80** [comment]
Im sorry if this is off topic and distacting. I am very interested in the
work you guy do, you have my respect. You guy are how ever a bit advanced
for me however. I do pride myself in my research abilities, but there
truely is no substitue for experiance. I trying ti put together a custom
recover and rom for the phone i have at the moment. Im sure that seems very
pedestrian to you all....lol However if anyone would be intetested in
pointing me in the right direction so to speak i would be eternally
greatfull.if not like i said, totally inderstandable. Other than that. If
it alright with everyone concerned id like to continue to watch your
progress, quietly ofcourse. Thank you for your time, and for your
consideration...chris

**Comment by unnawut** [comment]
@MIKEISCHRIS80 I'm not sure I understand what you want to do. For something that's as high-level as this, it's probably best to take it in our Gitter room first: https://gitter.im/omisego/ewallet.

**Comment by unnawut** [comment]
Everyone else, I hijacked this PR to include replacements of Rocket Chat -> Gitter as well.

**Pull request merged**
