### PR TITLE
More descriptive invalid parameter errors

### PR DESCRIPTION
**Pull request by jimpeebles**
Issue/Task Number: #774

# Overview

Added descriptions where none were given for client:invalid_parameter errors and included more information about missing or invalid parameters.

# Changes

Changes to error descriptions in many test files, see commits for more granular detail

# Implementation Details

Added and modified descriptions

# Usage

Ensure that all descriptions match the particular error being thrown. Was basing decisions off immediate context.

# Impact

Should provide more information for debugging once merged.

# Notes

Didn't want my only contribution to be fixing copyright dates. Hopefully you find this useful (and accurate!)

### CODE REVIEW

**Comment by sirn** [comment]
Thank you for this! ❤️ 

This one probably need @T-Dnzt's review, but he won't be around until Wednesday, so it's going to take a bit longer to merge. Sorry about this!

**Comment by unnawut** [comment]
Thanks for the PR. It's looking good so far!

The changes so far cover only the tests, which means that the actual implementation will not be producing these messages yet and the test assertions will fail.

Do you mind have a look at this [`TokenController`](https://github.com/omisego/ewallet/blob/master/apps/admin_api/lib/admin_api/v1/controllers/token_controller.ex)? It contains both the error handlers that return a generic and a specific description.

For example, this one returns a generic error description:

```elixir
  def get(conn, %{"id" => id}) do
    # /token.get implementation
  end

  def get(conn, _), do: handle_error(conn, :invalid_parameter)
```

Versus this one returns a specific error description:

```elixir
  def update(conn, %{"id" => id} = attrs) do
    # /token.update implementation
  end

  def update(conn, _) do
    handle_error(conn, :invalid_parameter, "Invalid parameter provided. `id` is required.")
  end
```

The former needs to be updated to something along the line of the latter.

Thanks again!

**Comment by jimpeebles** [comment]
Thanks for the feedback! Excuse my ignorance, this is my first experience with elixir (and a real CI process). Your example makes sense, will make appropriate changes.

**Comment by jimpeebles** [comment]
@unnawut Quick question - I saw that the release versioning strategy got changed. Should PR's for this issue be against master or v1.2 release?

**Comment by unnawut** [comment]
Good catch! Yes please target against `master`!

**Comment by jimpeebles** [comment]
@unnawut I'm closing this PR for now - have not had enough spare time to work on it and I don't want to hold up development. Sorry for the delay, hopefully I'll have more time in the future to contribute.

**Comment by unnawut** [comment]
Ah sorry to hear and I totally understand that! It turns out to be a pretty complicate task.

If you ever feel like having another go at something on this project, I've been tagging more tasks with [`good first issue`](https://github.com/omisego/ewallet/labels/flag%2Fgood%20first%20issue%20%3Achildren_crossing%3A). Feel free to have a look at them whenever you like :)

Thanks again for your help!

**Comment by jimpeebles** [comment]
Thanks, I'll definitely check those out! Do you have a vagrantfile with the proper config for the ewallet? Was experiencing some small issues with encoding, probably due to my poorly configured linux environment.

If there's another workflow that's more appropriate, please let me know!

**Comment by unnawut** [comment]
@jimpeebles We've moved to docker-compose now, which has much smaller footprint than vagrant. The [Getting Started](https://github.com/omisego/ewallet#getting-started) guide should set you up for it.

Although that docker-compose file is tailored for those who won't be touching the codebase. So after step 3, you can sync your generated `docker-compose.override.yml` file with values from my [gist](https://gist.github.com/unnawut/8ac413dc16c53c03f6f38b1dde7240ed).

Once done, you can `docker-compose up -d` followed by `docker-compose exec ewallet bash` which will get you into the docker environment.

**Comment by jimpeebles** [comment]
Perfect, just what I was looking for. Thanks!

**Pull request closed without merging**
