### PR TITLE
Improve seeding output

### PR DESCRIPTION
**Pull request by unnawut**
Issue/Task Number: T126, T127

# Overview

Make output of `mix seed` and `mix seed --sample` more consistent. Add `--verbose` option to list out the actual data inserted by the seed.

# Changes

- Prepend `mix seed --sample` output with `mix seed`
- Add `--verbose` option so that users can see what is inserted

# Implementation Details

The seed output could be much leaner but since the seed is still working in place of the admin panel (e.g. API key creation), we still need the seed output. Once the admin panel has all the features that the seed does, then we can simplify the output much more. 

# Usage

- Run `mix seed --sample` to see the prepended seed output.
- Run `mix seed --verbose` or `mix seed --sample --verbose` to show the data inserted by the seed.

### Example screenshot (ran locally, credentials are no longer valid):
image

### Full output (`mix seed`)

```sh
vagrant@ewallet:/vagrant$ mix seed
What email address should we set for your first admin user?
This email is required for logging into the admin panel.
If a user with this email already exists, it will escalate the user to admin role.

E-mail (admin@example.com): custom@email.com

                     Setting up the OmiseGO eWallet Server

This seeder seeds the minimum amount of data needed to start a production environment.

If you would like to seed the database with sample data so that you can play around with the
system, we recommend running mix seed --sample instead.

## Manage your eWallet system via the Admin Panel

We have just seeded your eWallet system with an API key and an Admin Panel user. To save your time,
we have also configured the Admin Panel with the seeded API key. If you want to, you can look up
the configuration file at apps/admin_panel/assets/.env.

Now it's your turn to login to your Admin Panel with the following credentials:

  • Login URL : http://localhost:4000/admin
  • Email     : custom@email.com
  • Password  : ZLiwRiWhylwEYCj2HQ7gJQ

Please take note of the above password. We won't be able to retrieve it again after the initial
seed, as it will be one-way encrypted for your security.

Now that you are logged in to the Admin Panel, you can:

  • Change your password immediately! The password will show in the seed only once.
  • Create other Admin Panel users
  • Manage access and secret keys for your application servers to connect to OmiseGO eWallet
    API
  • Manage API keys for your mobile apps and the Admin Panel
  • Always come back and access your Admin Panel at http://localhost:4000/admin
  • etc.

## Manage your eWallet system via the Admin API

The Admin API is the entry point to manage the entire OmiseGO eWallet system. Follow the steps
below to authenticate your Swagger UI requests:

  1. Browse to http://localhost:4000/admin/api/docs and click Authorize
  2. Use the value below for ClientAuth and click Authorize:
         OMGAdmin MDMyYjE2NTktZWJlNS00ZTIzLWFkNGEtOWIzNDY5ZDBkYTU5Om96bU9NaGtERkc4RmRoZUJIclRiUWpTZlFjVEcyaWFmcV9SY3k0MUhPWlk=

     Note: You can also make requests from your favorite API client by building your own
     Authorization header:

     • Authorization header : OMGAdmin base64(api_key_id:api_key)
     • API key ID           : 032b1659-ebe5-4e23-ad4a-9b3469d0da59
     • API key              : ozmOMhkDFG8FdheBHrTbQjSfQcTG2iafq_Rcy41HOZY

  3. Now you can call the /login endpoint with the above Authorization header and the
     following request body:
         {
          "email": "custom@email.com",
          "password": "ZLiwRiWhylwEYCj2HQ7gJQ"
         }

     Please take note of the above password. We won't be able to retrieve it again after the
     initial seed, as it will be one-way encrypted for your security.

  4. To get started quickly, we have seeded the user's authentication token and generated the
     Authorization header for you. Browse to http://localhost:4000/admin/api/docs again and click
     Authorize. This time, use the value below for UserAuth:
         OMGAdmin MDMyYjE2NTktZWJlNS00ZTIzLWFkNGEtOWIzNDY5ZDBkYTU5Om96bU9NaGtERkc4RmRoZUJIclRiUWpTZlFjVEcyaWFmcV9SY3k0MUhPWlk6NDI4OWMzMmEtMGJkMC00YzVjLTlmMTktZWU0NjY0ZDE1MDIzOk1BX0pCTzZGRlBTSy1ZajQzQzhFTmRWM0ZCal94dzlHdlNoa0JmYzROM0U=

     The above header is for you to get started quickly. To integrate the eWallet SDK to your
     application, you must build your own Authorization header using the information below:

     • Authorization header : OMGAdmin base64(api_key_id:api_key:user_id:auth_token)
     • API key ID           : 032b1659-ebe5-4e23-ad4a-9b3469d0da59
     • API key              : ozmOMhkDFG8FdheBHrTbQjSfQcTG2iafq_Rcy41HOZY
     • User ID              : <the returned user_id in step 3>
     • User's auth token    : <the returned authentication_token in step 3>

  5. Test your authentication by calling /me.get. You should see your user information.

## Using the eWallet API

Now that you are authenticated, you have the full access to the eWallet system via the Admin API.
You can now use the Authorization header above with the rest of the Swagger specification at
http://localhost:4000/admin/api/docs to:

  • Generate a pair of access/secret key for your application servers via /access_key.create
  • Generate a pair of API key for your clients such as your mobile app, via /api_key.create
  • Use the API key generated above to make requests to the eWallet API. Learn more at
    http://localhost:4000/api/docs
  • etc.

Database seeded completed. Enjoy!
```

### Full output (`mix seed --verbose`)

```sh
vagrant@ewallet:/vagrant$ mix seed --verbose
What email address should we set for your first admin user?
This email is required for logging into the admin panel.
If a user with this email already exists, it will escalate the user to admin role.

E-mail (admin@example.com): custom@email.com

                      Verbose mode: Displaying seeded data

Seeding the master account:

  Name : master_account
  ID   : 8dc0712e-87b9-443e-a72b-e01f27039110

Seeding an Admin Panel API key:

  Account ID : 8dc0712e-87b9-443e-a72b-e01f27039110
  API key ID : ac5cd4ea-7d74-4e1f-bb79-5cc54d314723
  API key    : YD-UdZ4xrNTOnyLA1lcy3FoiRbHwJIX_QZKzwpj-4ro

Seeding roles:

  Name         : admin
  Display name : Admin

  Name         : viewer
  Display name : Viewer

Seeding the initial admin panel user:

  ID       : f45e3962-f2bf-41ea-873b-890f93fc94ef
  Email    : custom@email.com
  Password : BtziE1wDM0ubhxZ_TnLL3w

  Email   : custom@email.com
  Account : master_account
  Role    : admin


                     Setting up the OmiseGO eWallet Server

This seeder seeds the minimum amount of data needed to start a production environment.

If you would like to seed the database with sample data so that you can play around with the
system, we recommend running mix seed --sample instead.

## Manage your eWallet system via the Admin Panel

We have just seeded your eWallet system with an API key and an Admin Panel user. To save your time,
we have also configured the Admin Panel with the seeded API key. If you want to, you can look up
the configuration file at apps/admin_panel/assets/.env.

Now it's your turn to login to your Admin Panel with the following credentials:

  • Login URL : http://localhost:4000/admin
  • Email     : custom@email.com
  • Password  : BtziE1wDM0ubhxZ_TnLL3w

Please take note of the above password. We won't be able to retrieve it again after the initial
seed, as it will be one-way encrypted for your security.

Now that you are logged in to the Admin Panel, you can:

  • Change your password immediately! The password will show in the seed only once.
  • Create other Admin Panel users
  • Manage access and secret keys for your application servers to connect to OmiseGO eWallet
    API
  • Manage API keys for your mobile apps and the Admin Panel
  • Always come back and access your Admin Panel at http://localhost:4000/admin
  • etc.

## Manage your eWallet system via the Admin API

The Admin API is the entry point to manage the entire OmiseGO eWallet system. Follow the steps
below to authenticate your Swagger UI requests:

  1. Browse to http://localhost:4000/admin/api/docs and click Authorize
  2. Use the value below for ClientAuth and click Authorize:
         OMGAdmin YWM1Y2Q0ZWEtN2Q3NC00ZTFmLWJiNzktNWNjNTRkMzE0NzIzOllELVVkWjR4ck5UT255TEExbGN5M0ZvaVJiSHdKSVhfUVpLendwai00cm8=

     Note: You can also make requests from your favorite API client by building your own
     Authorization header:

     • Authorization header : OMGAdmin base64(api_key_id:api_key)
     • API key ID           : ac5cd4ea-7d74-4e1f-bb79-5cc54d314723
     • API key              : YD-UdZ4xrNTOnyLA1lcy3FoiRbHwJIX_QZKzwpj-4ro

  3. Now you can call the /login endpoint with the above Authorization header and the
     following request body:
         {
          "email": "custom@email.com",
          "password": "BtziE1wDM0ubhxZ_TnLL3w"
         }

     Please take note of the above password. We won't be able to retrieve it again after the
     initial seed, as it will be one-way encrypted for your security.

  4. To get started quickly, we have seeded the user's authentication token and generated the
     Authorization header for you. Browse to http://localhost:4000/admin/api/docs again and click
     Authorize. This time, use the value below for UserAuth:
         OMGAdmin YWM1Y2Q0ZWEtN2Q3NC00ZTFmLWJiNzktNWNjNTRkMzE0NzIzOllELVVkWjR4ck5UT255TEExbGN5M0ZvaVJiSHdKSVhfUVpLendwai00cm86ZjQ1ZTM5NjItZjJiZi00MWVhLTg3M2ItODkwZjkzZmM5NGVmOjRvRGtDeTZqZTQwYndJVU5OQV8wLUhaU2k5NkExZ3E3VnB6Sk1ULWh1cm8=

     The above header is for you to get started quickly. To integrate the eWallet SDK to your
     application, you must build your own Authorization header using the information below:

     • Authorization header : OMGAdmin base64(api_key_id:api_key:user_id:auth_token)
     • API key ID           : ac5cd4ea-7d74-4e1f-bb79-5cc54d314723
     • API key              : YD-UdZ4xrNTOnyLA1lcy3FoiRbHwJIX_QZKzwpj-4ro
     • User ID              : <the returned user_id in step 3>
     • User's auth token    : <the returned authentication_token in step 3>

  5. Test your authentication by calling /me.get. You should see your user information.

## Using the eWallet API

Now that you are authenticated, you have the full access to the eWallet system via the Admin API.
You can now use the Authorization header above with the rest of the Swagger specification at
http://localhost:4000/admin/api/docs to:

  • Generate a pair of access/secret key for your application servers via /access_key.create
  • Generate a pair of API key for your clients such as your mobile app, via /api_key.create
  • Use the API key generated above to make requests to the eWallet API. Learn more at
    http://localhost:4000/api/docs
  • etc.

Database seeded completed. Enjoy!
```

### Full output (`mix seed --sample --verbose`)

```sh
vagrant@ewallet:/vagrant$ mix seed --sample --verbose
What email address should we set for your first admin user?
This email is required for logging into the admin panel.
If a user with this email already exists, it will escalate the user to admin role.

E-mail (admin@example.com): custom@email.com

                      Verbose mode: Displaying seeded data

Seeding the master account:

  Name : master_account
  ID   : 50d901d5-3cac-4e37-b097-67be0a88833b

Seeding an Admin Panel API key:

  Account ID : 50d901d5-3cac-4e37-b097-67be0a88833b
  API key ID : 35c3fa8c-69a6-4892-924f-fd38d33674b5
  API key    : I9SgyO5l30ftBeS_Y5a4Is3u60mTNZFOZRSklKZz2Sk

Seeding roles:

  Name         : admin
  Display name : Admin

  Name         : viewer
  Display name : Viewer

Seeding the initial admin panel user:

  ID       : 965eb181-6e83-442d-adce-4b68f4d0374f
  Email    : custom@email.com
  Password : HfhFsCyQfBb-dwjajeND9A

  Email   : custom@email.com
  Account : master_account
  Role    : admin


                     Setting up the OmiseGO eWallet Server

This seeder seeds the minimum amount of data needed to start a production environment.

If you would like to seed the database with sample data so that you can play around with the
system, we recommend running mix seed --sample instead.

## Manage your eWallet system via the Admin Panel

We have just seeded your eWallet system with an API key and an Admin Panel user. To save your time,
we have also configured the Admin Panel with the seeded API key. If you want to, you can look up
the configuration file at apps/admin_panel/assets/.env.

Now it's your turn to login to your Admin Panel with the following credentials:

  • Login URL : http://localhost:4000/admin
  • Email     : custom@email.com
  • Password  : HfhFsCyQfBb-dwjajeND9A

Please take note of the above password. We won't be able to retrieve it again after the initial
seed, as it will be one-way encrypted for your security.

Now that you are logged in to the Admin Panel, you can:

  • Change your password immediately! The password will show in the seed only once.
  • Create other Admin Panel users
  • Manage access and secret keys for your application servers to connect to OmiseGO eWallet
    API
  • Manage API keys for your mobile apps and the Admin Panel
  • Always come back and access your Admin Panel at http://localhost:4000/admin
  • etc.

## Manage your eWallet system via the Admin API

The Admin API is the entry point to manage the entire OmiseGO eWallet system. Follow the steps
below to authenticate your Swagger UI requests:

  1. Browse to http://localhost:4000/admin/api/docs and click Authorize
  2. Use the value below for ClientAuth and click Authorize:
         OMGAdmin MzVjM2ZhOGMtNjlhNi00ODkyLTkyNGYtZmQzOGQzMzY3NGI1Okk5U2d5TzVsMzBmdEJlU19ZNWE0SXMzdTYwbVROWkZPWlJTa2xLWnoyU2s=

     Note: You can also make requests from your favorite API client by building your own
     Authorization header:

     • Authorization header : OMGAdmin base64(api_key_id:api_key)
     • API key ID           : 35c3fa8c-69a6-4892-924f-fd38d33674b5
     • API key              : I9SgyO5l30ftBeS_Y5a4Is3u60mTNZFOZRSklKZz2Sk

  3. Now you can call the /login endpoint with the above Authorization header and the
     following request body:
         {
          "email": "custom@email.com",
          "password": "HfhFsCyQfBb-dwjajeND9A"
         }

     Please take note of the above password. We won't be able to retrieve it again after the
     initial seed, as it will be one-way encrypted for your security.

  4. To get started quickly, we have seeded the user's authentication token and generated the
     Authorization header for you. Browse to http://localhost:4000/admin/api/docs again and click
     Authorize. This time, use the value below for UserAuth:
         OMGAdmin MzVjM2ZhOGMtNjlhNi00ODkyLTkyNGYtZmQzOGQzMzY3NGI1Okk5U2d5TzVsMzBmdEJlU19ZNWE0SXMzdTYwbVROWkZPWlJTa2xLWnoyU2s6OTY1ZWIxODEtNmU4My00NDJkLWFkY2UtNGI2OGY0ZDAzNzRmOmlrYWs1Q2dyN2Utd3VIb2prZTJEOUJvRXRjLVVaWG9yZG5DbDVRWjdVbFk=

     The above header is for you to get started quickly. To integrate the eWallet SDK to your
     application, you must build your own Authorization header using the information below:

     • Authorization header : OMGAdmin base64(api_key_id:api_key:user_id:auth_token)
     • API key ID           : 35c3fa8c-69a6-4892-924f-fd38d33674b5
     • API key              : I9SgyO5l30ftBeS_Y5a4Is3u60mTNZFOZRSklKZz2Sk
     • User ID              : <the returned user_id in step 3>
     • User's auth token    : <the returned authentication_token in step 3>

  5. Test your authentication by calling /me.get. You should see your user information.

## Using the eWallet API

Now that you are authenticated, you have the full access to the eWallet system via the Admin API.
You can now use the Authorization header above with the rest of the Swagger specification at
http://localhost:4000/admin/api/docs to:

  • Generate a pair of access/secret key for your application servers via /access_key.create
  • Generate a pair of API key for your clients such as your mobile app, via /api_key.create
  • Use the API key generated above to make requests to the eWallet API. Learn more at
    http://localhost:4000/api/docs
  • etc.


                  Verbose mode: Displaying seeded sample data

Seeding Accounts:

  Name   : brand1
  ID     : 2a311097-7690-4f45-811b-1e7fd2568221
  Parent : 50d901d5-3cac-4e37-b097-67be0a88833b

  Name   : branch1
  ID     : c957604c-9b67-49f1-846f-b3a5ca602a08
  Parent : 2a311097-7690-4f45-811b-1e7fd2568221

  Name   : brand2
  ID     : 601622d7-5516-4bad-9a0c-e78df61f4240
  Parent : 50d901d5-3cac-4e37-b097-67be0a88833b

  Name   : branch2
  ID     : 66c20fd5-8121-4f2e-ba22-26720b610890
  Parent : 601622d7-5516-4bad-9a0c-e78df61f4240

Seeding the minted tokens:

  Friendly ID     : OMG:85c479a9-c246-4d85-8d55-3ec5fab29cb8
  Subunit to unit : 10000
  Account         : 50d901d5-3cac-4e37-b097-67be0a88833b

  Friendly ID     : KNC:7e12e77d-319e-48c5-8445-403e8dee52c7
  Subunit to unit : 1000
  Account         : 50d901d5-3cac-4e37-b097-67be0a88833b

  Friendly ID     : BTC:62dfb823-0a2e-4b91-8042-c6e05f3f46b8
  Subunit to unit : 10000
  Account         : 50d901d5-3cac-4e37-b097-67be0a88833b

  Friendly ID     : OEM:6c2798ef-34eb-4462-ab1f-2606a07eef3c
  Subunit to unit : 100
  Account         : 50d901d5-3cac-4e37-b097-67be0a88833b

  Friendly ID     : ETH:66ff7ca6-0829-473e-9c62-2932518787ce
  Subunit to unit : 1000000000000000000
  Account         : 50d901d5-3cac-4e37-b097-67be0a88833b

Minting the seeded minted tokens:

  Minted Token ID  : OMG:85c479a9-c246-4d85-8d55-3ec5fab29cb8
  Amount (subunit) : 10000000000
  Confirmed?       : true
  From address     : genesis
  To address       : c51bc034-a0fb-40e1-a36f-ce330cd36feb

  Minted Token ID  : KNC:7e12e77d-319e-48c5-8445-403e8dee52c7
  Amount (subunit) : 1000000000
  Confirmed?       : true
  From address     : genesis
  To address       : c51bc034-a0fb-40e1-a36f-ce330cd36feb

  Minted Token ID  : BTC:62dfb823-0a2e-4b91-8042-c6e05f3f46b8
  Amount (subunit) : 10000000000
  Confirmed?       : true
  From address     : genesis
  To address       : c51bc034-a0fb-40e1-a36f-ce330cd36feb

  Minted Token ID  : OEM:6c2798ef-34eb-4462-ab1f-2606a07eef3c
  Amount (subunit) : 100000000
  Confirmed?       : true
  From address     : genesis
  To address       : c51bc034-a0fb-40e1-a36f-ce330cd36feb

  Minted Token ID  : ETH:66ff7ca6-0829-473e-9c62-2932518787ce
  Amount (subunit) : 1000000000000000000000000
  Confirmed?       : true
  From address     : genesis
  To address       : c51bc034-a0fb-40e1-a36f-ce330cd36feb

Seeding eWallet users:

  User ID          : 4cec7574-8327-4b34-838a-3af6f08602ed
  Provider user ID : provider_user_id01
  Username         : user01

  User ID          : 081b16c9-e419-4c24-a87a-ec7c9e58c04e
  Provider user ID : provider_user_id02
  Username         : user02

  User ID          : 57df7bde-968d-4e26-bf49-5f60e3998c6c
  Provider user ID : provider_user_id03
  Username         : user03

  User ID          : 4819abb8-29bf-47dc-aa4a-b289fd05a2a3
  Provider user ID : provider_user_id04
  Username         : user04

  User ID          : e3eb0672-1625-4030-9dc6-0a94c1353f9d
  Provider user ID : provider_user_id05
  Username         : user05

Seeding admin panel users:

  Email    : admin_brand1@example.com
  Password : P1wVht3lQSgPEBGnJ6ECzA
  ID       : cefa496a-a902-4e43-9460-7e956480e63b

  Email    : admin_branch1@example.com
  Password : d7XLP3RKMAHWPIz1G4nKdg
  ID       : f6f7792b-86f1-4488-998c-7072b4e3a329

  Email    : viewer_master@example.com
  Password : L_wn_QHqsDU32Nb1Fp1bEQ
  ID       : 63eb352f-9f3c-4978-a976-24e070a42f84

  Email    : viewer_brand1@example.com
  Password : SFy6aGAWcjcWqnJyyXCkPQ
  ID       : 7cc92e85-ab2d-4d94-b75f-b2b6265a3ccd

  Email    : viewer_branch1@example.com
  Password : nPhdvReUE7nqTmLgarF8bw
  ID       : 3dc49a9b-1531-4f0f-b3c3-82fd775bdbe4

Assigning roles to admin panel users:

  Email : admin_brand1@example.com
  Role  : admin at brand1

  Email : admin_branch1@example.com
  Role  : admin at branch1

  Email : viewer_master@example.com
  Role  : viewer at master_account

  Email : viewer_brand1@example.com
  Role  : viewer at brand1

  Email : viewer_branch1@example.com
  Role  : viewer at branch1

Seeding Access/Secret Keys:

  Account    : master_account
  Access key : orgKE14U6eH-v-qL3IATAxhwCJsK_t36INJ_EROZQI0
  Secret key : XsLduV_L5vbEippXuC3lm5_5y5LGTRGysHUL3XSjaQU

Seeding API Keys:

  Owner app  : ewallet_api
  Account    : master_account (50d901d5-3cac-4e37-b097-67be0a88833b)
  API key ID : 0f50c2c4-fcbe-404f-9249-bb2713b16ac9
  API key    : qM5lSwlGb8ThqXyhJGBIzuNG26JvMVPMOdYReodgrjY

Seeding Auth Tokens:

  Owner app        : ewallet_api
  User ID          : 4cec7574-8327-4b34-838a-3af6f08602ed
  Provider user ID : provider_user_id01
  User email       : <nil>
  Auth token       : anjePBrx-3mi8vRffKFIfy_OYlwhr8-JOxWjID9M6xI

  Owner app        : admin_api
  User ID          : 965eb181-6e83-442d-adce-4b68f4d0374f
  Provider user ID : <nil>
  User email       : custom@email.com
  Auth token       : x1kMkX02XLH4Gf5jdr05ZN4wIYFMm-8TVeo8vp0XCgA


               Trying out OmiseGO eWallet Server with sample data

As you have just run the seed with --sample option, we have generated some credentails below for
you to try the endpoints easily.

If you would like to seed the database with the minimum amount needed to start a production
environment, we recommend running mix seed instead.

## Try eWallet API's Server endpoints

  1. Browse to http://localhost:4000/api/docs
  2. Click the Authorize button
  3. Use the value below for ServerAuth:

    OMGServer b3JnS0UxNFU2ZUgtdi1xTDNJQVRBeGh3Q0pzS190MzZJTkpfRVJPWlFJMDpYc0xkdVZfTDV2YkVpcHBYdUMzbG01XzV5NUxHVFJHeXNIVUwzWFNqYVFV

  4. Try out Server endpoints such as /login, /user.create, /transfer, etc.

## Try eWallet API's Client endpoints

  1. Browse to http://localhost:4000/api/docs
  2. Click the Authorize button
  3. Use the value below for ClientAuth:

    OMGClient cU01bFN3bEdiOFRocVh5aEpHQkl6dU5HMjZKdk1WUE1PZFlSZW9kZ3JqWTphbmplUEJyeC0zbWk4dlJmZktGSWZ5X09ZbHdocjgtSk94V2pJRDlNNnhJ

  4. Try out Client endpoints such as /me.get, /me.list_transactions, /logout, etc.

## Try Admin API's Client endpoints

  1. Browse to http://localhost:4000/admin/api/docs
  2. Click the Authorize button
  3. Use the value below for ClientAuth:

    OMGAdmin MzVjM2ZhOGMtNjlhNi00ODkyLTkyNGYtZmQzOGQzMzY3NGI1Okk5U2d5TzVsMzBmdEJlU19ZNWE0SXMzdTYwbVROWkZPWlJTa2xLWnoyU2s=

  4. Try out Client endpoints such as /login, /password.reset, /password.update, etc.

## Try Admin API's User endpoints

  1. Browse to http://localhost:4000/admin/api/docs
  2. Click the Authorize button
  3. Use the value below for UserAuth:

    OMGAdmin MzVjM2ZhOGMtNjlhNi00ODkyLTkyNGYtZmQzOGQzMzY3NGI1Okk5U2d5TzVsMzBmdEJlU19ZNWE0SXMzdTYwbVROWkZPWlJTa2xLWnoyU2s6OTY1ZWIxODEtNmU4My00NDJkLWFkY2UtNGI2OGY0ZDAzNzRmOngxa01rWDAyWExINEdmNWpkcjA1Wk40d0lZRk1tLThUVmVvOHZwMFhDZ0E=

  4. Try out User endpoints such as /account.create, /account.assign_user, /access_key.create,
     etc.

Database seeded completed. Enjoy!
```

# Impact

Usual deployment.

### CODE REVIEW

**Comment by unnawut** [comment]
Good idea. Let me do that.

**Comment by unnawut** [comment]
@T-Dnzt Please try again.

Note that there's a bit of flickering when typing the password because there's no built-in implementation for password input so we need to [repeatedly clear the input in a loop](https://stackoverflow.com/questions/37720961/elixir-or-erlang-prompt-for-password-with-hidden-input) :(

image

**Comment by T-Dnzt** [comment]
@unnawut Can we specify that the password needs to be 8 chars long and not crash the seeds if they enter an incorrect password? :)

Also, I guess we can't get rid of the `^R` when deleting characters?

```
E-mail (admin@example.com): thibault@omise.co
Password (autogenerate if not given): ^R
Password (autogenerate if not given): ^R
Password (autogenerate if not given): ^R
Password (autogenerate if not given): ^R
Password (autogenerate if not given):
The password must be 8 characters or more.
```

**Comment by unnawut** [comment]
@T-Dnzt Now the seeder would re-ask for inputs rather than exiting.

As for `^R`, I can't reproduce either on Terminal nor iTerm2 on macOS 10.13.3 :(

**Pull request merged**
